### ISSUE TITLE
Ubports X00TD rootfs has extremely low disk space

### ISSUE THREAD

**Issue by marohinmark** [Linux-On-Sdm6Series/android#1]
There is 20 GB disk space on my phone, but rootfs has fixed size and says about low disk space.

**Comment by iAboothahir** [comment]
You can goto custom recovery then open terminal windows
give these two command 
e2fsck -fy /data/rootfs.img;
resize2fs /data/rootfs.img 12G;
Note: you can

**Comment by iAboothahir** [comment]
Goto custom recovery then type these commands on recovery terminal

e2fsck -fy /data/rootfs.img;
resize2fs /data/rootfs.img 12G;

NOTE :The above command resize your rootfs to 12GB

**Comment by marohinmark** [comment]
Thanks a lot.

**Comment by marohinmark** [comment]
And, is _apt user really needed?

**Comment by dopaemon** [comment]
> And, is _apt user really needed?

sudo apt adduser _apt --force-badname
sudo usermod -aG sudo _apt
